version: '3.8'
services:
  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: dinner_dash
    ports:
      - '5432:5432'
    volumes:
      - dinner-dash-db:/var/lib/postgresql/data

  web:
    build: .
    command:
      sh -c "bundle exec rake db:migrate 2>/dev/null || bundle exec rake db:create db:migrate && rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    depends_on:
      - db
      - webpacker
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: dinner_dash
      POSTGRES_HOST: db
      NODE_ENV: development
      RAILS_ENV: development
    volumes:
      - .:/workdir
      - /workdir/node_modules/
      - bundler_gems:/usr/local/bundle/

  webpacker:
    build: .
    environment:
      NODE_ENV: development
      RAILS_ENV: development
    command: ./bin/webpack-dev-server
    volumes:
      - .:/workdir
      - /workdir/node_modules/
      - bundler_gems:/usr/local/bundle/
    ports:
      - '3035:3035'

volumes:
  dinner-dash-db:
  bundler_gems:
